feat: добавить controllers, films, users (ТЗ-9)
DenisPolo/java-filmorate pull request #6
Opened 2023-04-03 17:06 UTC by DenisPolo

Добавлены классы film и user, а также контроллеры

2023-04-04 13:07 UTC, andrew-larkin requested changes
Привет! Отличная работа, реализация на достаточно хорошем уровне, а за добавленные аннотации отдельный плюс. Пара архитектурных правок и мы будем готовы двигаться дальше

2023-04-04 13:07 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@RequestMapping()
можно здесь в скобках прописать /films и тогда в методах маппинги можно оставить пустыми

2023-04-04 13:07 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReleaseValidation.java
> +public @interface ReleaseValidation {
валидаторы и аннотации предалагаю вынести в отдельную папку validators

2023-04-04 13:07 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +public class FilmorateApplicationTests {
давай также разделим тесты контроллеров на 2 класса: UserControllerTest и FilmControllerTest

2023-04-05 11:55 UTC, DenisPolo commented
Привет! Исправил проект по всем замечаниям.

2023-04-10 02:52 UTC, merged